Adds a crossing with a lane turning to the right.
maliput/maliput_xodr pull request #36
Opened 2023-08-30 16:21 UTC by agalbachicar

# 🎉 New feature

Closes #29 

## Summary

Solves the following map:

![image](https://github.com/maliput/maliput_xodr/assets/3825465/9b598454-16e7-4e62-89ad-8062879d1213)

## Test it

Following the instructions in the readme, you can reproduce the map.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-08-30 16:48 UTC, liangfok commented
Thanks for creating this! I'll test it ASAP.

2023-08-30 17:20 UTC, francocipollone requested changes
Just some comments to go!

2023-08-30 17:23 UTC, francocipollone commented
One extra comment, you can add the generation of this map to the tool script: https://github.com/maliput/maliput_xodr/blob/main/tools/update_resources.sh

2023-08-30 17:37 UTC, francocipollone commented on templates/dedicated_turn_lanes_going_north_and_south.em
> +                            <vectorLane travelDir="forward"/>
Addressed at [ef2e64d](https://github.com/maliput/maliput_xodr/pull/36/commits/ef2e64dcb084b7d48e853f497bc330eab7780b4e)

2023-08-30 17:37 UTC, francocipollone commented on templates/dedicated_turn_lanes_going_north_and_south.em
> +                            <vectorLane travelDir="backward"/>
Addressed at [ef2e64d](https://github.com/maliput/maliput_xodr/pull/36/commits/ef2e64dcb084b7d48e853f497bc330eab7780b4e)

2023-08-30 17:37 UTC, francocipollone commented on templates/dedicated_turn_lanes_going_north_and_south.em
> +                            <vectorLane travelDir="backward"/>
Addressed at [ef2e64d](https://github.com/maliput/maliput_xodr/pull/36/commits/ef2e64dcb084b7d48e853f497bc330eab7780b4e)

2023-08-30 17:37 UTC, francocipollone commented on templates/dedicated_turn_lanes_going_north_and_south.em
> +                            <vectorLane travelDir="forward"/>
Addressed at [ef2e64d](https://github.com/maliput/maliput_xodr/pull/36/commits/ef2e64dcb084b7d48e853f497bc330eab7780b4e)

2023-08-30 17:37 UTC, francocipollone commented on templates/dedicated_turn_lanes_going_north_and_south.em
> +                            <vectorLane travelDir="forward"/>
Addressed at [ef2e64d](https://github.com/maliput/maliput_xodr/pull/36/commits/ef2e64dcb084b7d48e853f497bc330eab7780b4e)

2023-08-30 17:37 UTC, francocipollone commented on templates/dedicated_turn_lanes_going_north_and_south.em
> +                            <vectorLane travelDir="backward"/>
Addressed at [ef2e64d](https://github.com/maliput/maliput_xodr/pull/36/commits/ef2e64dcb084b7d48e853f497bc330eab7780b4e)

2023-08-30 17:37 UTC, francocipollone commented on templates/dedicated_turn_lanes_going_north_and_south.em
> +  lon_lat_points.append(lon_lat_points[0]) # GeoJSON format needs closure
Addressed at [ef2e64d](https://github.com/maliput/maliput_xodr/pull/36/commits/ef2e64dcb084b7d48e853f497bc330eab7780b4e)

2023-08-30 17:38 UTC, francocipollone approved these changes, later dismissed
LGTM

2023-08-30 17:39 UTC, francocipollone commented
> Thanks for creating this! I'll test it ASAP.

@liangfok , I pushed some fixes mainly related to the traffic direction rules. For testing use the latest files that I now pushed.

2023-08-30 17:43 UTC, liangfok commented
Got it. I just grabbed the latest revision. Thanks for the note.

2023-09-12 16:25 UTC, francocipollone commented
Gently ping to check if this PR is mergeable as it is. @liangfok

2023-09-12 16:52 UTC, liangfok commented
This is still undergoing the initial review, but based on work in #37, I will likely have to re-generate the map using our downstreawm tooling once our downstream tooling supports stop lines with and without stop signs. I'm going to wait for #37 to pass initial testing before refocusing on this map.

2023-09-26 17:14 UTC, francocipollone commented
> This is still undergoing the initial review, but based on work in #37, I will likely have to re-generate the map using our downstreawm tooling once our downstream tooling supports stop lines with and without stop signs. I'm going to wait for #37 to pass initial testing before refocusing on this map.

Friendly ping @liangfok . Based on this result, is it necessary to update something here?

2023-09-26 17:27 UTC, francocipollone commented
> I continue to wait for our downstream users to evaluate this map. This particular map is a lower priority for them, so it might be a while before they have the cycles to evaluate it. They are just starting to use the map in [54a70d4](https://github.com/maliput/maliput_xodr/commit/54a70d490ae540ea7409224025a444a859a6f762).

Great! Thanks for the update! Let's wait for the feedback then.

2023-12-06 19:19 UTC, francocipollone commented
I need to fix minor conflicts due to the last PRs that got merged. However, let me know if this PR is mergeable @liangfok

2023-12-06 19:48 UTC, liangfok commented
Will do. Currently our downstream users are focused on other maps, but will definitely return to this one in the future.

2024-01-31 23:13 UTC, liangfok commented
Let's rename this map "dual_opposing_dedicated_right_turn_lanes." This is to highlight the fact that the dedicated turn lanes are right turn lanes rather than left turn lanes, which is more important than the fact that they are oriented North/South.

2024-02-01 19:10 UTC, francocipollone commented
> Let's rename this map "dual_opposing_dedicated_right_turn_lanes." This is to highlight the fact that the dedicated turn lanes are right turn lanes rather than left turn lanes, which is more important than the fact that they are oriented North/South.

Done.

2024-02-01 19:10 UTC, francocipollone commented
Ready to review @liangfok

2024-02-05 20:03 UTC, liangfok commented
Just a quick note that @max-shaan is helping out with the downstream usage of this map.

2024-02-13 17:36 UTC, liangfok commented
I confirm we want to model both dedicated right-turn lanes, see attached screenshot.

![model_2nd_dedicated_right_turn](https://github.com/maliput/maliput_xodr/assets/1388098/c2b4365c-a277-4ec5-b602-beaf384bb107)

Side note: No need to annotate any lanes as having oncoming traffic. We can add that later when the need arises.

2024-02-20 18:48 UTC, francocipollone commented
@liangfok 

 - Requested changes were addressed:
![image](https://github.com/maliput/maliput_xodr/assets/53065142/05bb6fa4-8634-44d9-a6bc-99295a1820c5)
 - Extended lead-in and lead-out to 300m

![image](https://github.com/maliput/maliput_xodr/assets/53065142/e59eff12-82f1-4953-b38f-18eafe8bf9a4)

2025-08-21 13:14 UTC, merged