Adds straight_road_with_crosswalk_integration.xodr map.
maliput/maliput_xodr pull request #58
Opened 2023-11-10 19:28 UTC by francocipollone

# 🎉 New feature

Related to #46 

## Summary
 - Adds straight_road_with_crosswalk_integration.xodr map.

![image](https://github.com/maliput/maliput_xodr/assets/53065142/84cf4898-d24d-4fcd-ad1d-55da4564d4d2)

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

2023-11-27 18:00 UTC, liangfok requested changes

2023-11-27 18:20 UTC, francocipollone commented on standalone/straight_road_with_crosswalk_integration/straight_road_with_crosswalk_integration.xodr
> +            <successor elementType="road" elementId="11" contactPoint="start"/>
Oh, that's a bug indeed, thanks for pointing that out, I will fix it.

2023-11-27 23:51 UTC, liangfok commented on standalone/straight_road_with_crosswalk_integration/straight_road_with_crosswalk_integration.xodr
> +            <successor elementType="road" elementId="11" contactPoint="start"/>
In our downstream use cases, we confirmed that after changing `elementId="11"` to `elementId="10"`, the map passed our tests.

2023-11-28 12:37 UTC, francocipollone commented on standalone/straight_road_with_crosswalk_integration/straight_road_with_crosswalk_integration.xodr
> +            <successor elementType="road" elementId="11" contactPoint="start"/>
Done [bb059ac](https://github.com/maliput/maliput_xodr/pull/58/commits/bb059ac127787e1622fcf18c6b49b767b48e93b2)

2023-11-28 12:37 UTC, francocipollone commented
> In our downstream use cases, we confirmed that after changing elementId="11" to elementId="10", the map passed our tests.

@liangfok Can we go ahead and merge this then?

2023-11-28 13:01 UTC, liangfok approved these changes
LGTM Thanks!

2023-11-28 13:21 UTC, merged